export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const VIEW_ARTICLE_SUCCESS = 'VIEW_ARTICLE_SUCCESS';
export const VIEW_ARTICLE_ERROR = 'VIEW_ARTICLE_ERROR';
export const BACKEND_URL = 'https://codepirates-ah-backend-staging.herokuapp.com';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';

export const VERSION = 'v1';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';
export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';
/** Social auth actions */
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const TWITTER_AUTH_SUCCESS = 'TWITTER_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const TWITTER_AUTH_FAIL = 'TWITTER_AUTH_FAIL';

// this will contain actions
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';

/** Single Article  actions */
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';

// rate article action types
export const RATE_ARTICLE_SUCCESS = 'RATE_ARTICLE_SUCCESS';
export const RATE_ARTICLE_FAIL = 'RATE_ARTICLE_FAIL';
// landing page
export const FETCH_ARTICLES_ON_LANDING_PAGE_SUCCESS = 'FETCH_ARTICLES_ON_LANDING_PAGE_SUCCES';
export const FETCH_ARTICLES_ON_LANDING_PAGE_ERROR = 'FETCH_ARTICLES_ON_LANDING_PAGE_ERROR';
export const FETCH_POPULAR_ARTICLES_ON_LANDING_PAGE_SUCCESS = 'FETCH_POPULAR_ARTICLES_ON_LANDING_PAGE_SUCCESS';
export const FETCH_POPULAR_ARTICLES_ON_LANDING_PAGE_ERROR = 'FETCH_POPULAR_ARTICLES_ON_LANDING_PAGE_ERROR';
// Search related actions
export const SEARCH_RESULTS_PENDING = 'SEARCH_RESULTS_PENDING';
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_ERROR = 'SEARCH_RESULTS_ERROR';
export const VIEW_SPECIFIC_USER_ARTICLES_SUCCESS = 'VIEW_SPECIFIC_USER_ARTICLES_SUCCESS';
export const VIEW_SPECIFIC_USER_ARTICLES_FAIL = 'VIEW_SPECIFIC_USER_ARTICLES_FAIL';
// Reset password actions
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// Like related actions
export const CLAP_PENDING = 'CLAP_PENDING';
export const CLAP_SUCCESS = 'CLAP_SUCCESS';
export const CLAP_ERROR = 'CLAP_ERROR';
export const DISLIKE_PENDING = 'DISLIKE_PENDING';
export const DISLIKE_SUCCESS = 'DISLIKE_SUCCESS';
export const DISLIKE_ERROR = 'DISLIKE_ERROR';

// comment on Article

export const COMMENT_ON_AN_ARTICLE_SUCCESS = 'COMMENT_ON_AN_ARTICLE_SUCCESS';
export const COMMENT_ON_AN_ARTICLE_ERROR = 'COMMENT_ON_AN_ARTICLE_ERROR';
export const FETCH_ALL_ARTICLE_COMMENTS_SUCCESS = 'FETCH_ALL_ARTICLE_COMMENTS_SUCCESS';
export const FETCH_ALL_ARTICLE_COMMENTS_ERROR = 'FETCH_ALL_ARTICLE_COMMENTS_ERROR';

export const REPLY_A_COMMENT_SUCCESS = 'REPLY_A_COMMENT_SUCCESS';
export const REPLY_A_COMMENT_ERROR = 'REPLY_A_COMMENT_ERROR';

// save user in the store
export const SAVE_USER_IN_THE_STORE = 'LOGIN_SUCCESS_AND_SAVE_USER';

// Search related actions
export const BOOKMARK_PENDING = 'BOOKMARK_PENDING';
export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
export const BOOKMARK_ERROR = 'BOOKMARK_ERROR';

// Update Article actions
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE';
export const UPDATE_EDIT_MODE = 'UPDATE_EDIT_MODE';
// bookmarks actions
export const FETCH_MY_BOOKMARKS_SUCCESS = 'FETCH_MY_BOOKMARKS_SUCCESS';
export const FETCH_MY_BOOKMARKS__FAIL = 'FETCH_MY_BOOKMARKS__FAIL';

// Report related actions
export const REPORT_PENDING = 'REPORT_PENDING';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_ERROR = 'REPORT_ERROR';
export const REPORTEDARTICLES_PENDING = 'REPORTEDARTICLES_PENDING';
export const REPORTEDARTICLES_SUCCESS = 'REPORTEDARTICLES_SUCCESS';
export const REPORTEDARTICLES_ERROR = 'REPORTEDARTICLES_ERROR';
