export default [
  {
    authorId: 1,
    slug: 'fakeslug2',
    title: 'faketitle2',
    description: 'fakedescription2',
    body:
      'Sed ut perspiciatis unde omnis iste natus?',
    favorited: true,
    favoritedcount: 12,
    flagged: true,
    images: ['dddd'],
    views: 4,
    createdAt: '2019-10-18T14:12:25.667Z',
    readtime: '5 min read',
    username: 'admin',
    userImage: null,
    timeCreated: '3 minutes ago',
  },
  {
    authorId: 1,
    slug: 'first',
    title: 'title1',
    description: 'description1',
    body: 'body1',
    favorited: false,
    favoritedcount: 0,
    flagged: false,
    images: [''],
    views: 1,
    createdAt: '2019-10-18T14:12:25.649Z',
    readtime: '1 min read',
    username: 'admin',
    userImage: null,
    timeCreated: '3 minutes ago',
  },
  {
    authorId: 2,
    slug: 'second',
    title: 'title2',
    description: 'description2',
    body: 'body2',
    favorited: false,
    favoritedcount: 0,
    flagged: false,
    images: ['ddd'],
    views: 1,
    createdAt: '2019-10-18T14:12:25.649Z',
    readtime: '1 min read',
    username: 'mike.anguandia',
    userImage: null,
    timeCreated: '3 minutes ago',
  },
  {
    authorId: 1,
    slug: 'third',
    title: 'title3',
    description: 'description3',
    body: 'body3',
    favorited: false,
    favoritedcount: 0,
    flagged: false,
    images: [''],
    views: 1,
    createdAt: '2019-10-18T14:12:25.649Z',
    readtime: '1 min read',
    username: 'admin',
    userImage: null,
    timeCreated: '3 minutes ago',
  },
  {
    authorId: 3,
    slug: 'fourth',
    title: 'title4',
    description: 'description4',
    body: 'body4',
    favorited: false,
    favoritedcount: 0,
    flagged: false,
    images: [''],
    views: 1,
    createdAt: '2019-10-18T14:12:25.649Z',
    readtime: '1 min read',
    username: 'username',
    userImage: null,
    timeCreated: '3 minutes ago',
  },
  {
    authorId: 1,
    slug: 'fakeslug',
    title: 'faketitle',
    description: 'fakedescription',
    body:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    favorited: true,
    favoritedcount: 12,
    flagged: true,
    images: ['dddd'],
    views: 4,
    createdAt: '2019-10-18T14:12:25.641Z',
    readtime: '1 min read',
    username: 'admin',
    userImage: null,
    timeCreated: '3 minutes ago',
  },
];
